"""Canonical instructions and independent expectations for the guided walk."""


def step(do, expect, *, prep=(), files=None, absent=(), records=None, no_action=None, special=None):
    return dict(do=do, expect=expect, prep=list(prep), files=files or {}, absent=list(absent),
                records=records or {}, no_action=no_action, special=special)


def case(key, title, *steps, setup=(), optional=None):
    return dict(key=key, title=title, steps=list(steps), setup=list(setup), optional=optional)


CLEAN = {"membership": "managed", "xy": "  "}
CASES = [
    case("initial", "Membership and status",
         step("Inspect root rows hovered and unhovered; use W/d for the status legend.",
              'clean/bad/link: C   ; local: CMM ; source: C M ; unmanaged/ignored: blank; remove-me: C D ; .config/.exact: C  *.',
              absent=["script-ran"], records={"clean": CLEAN, "local": {"xy": "MM"}, "source": {"xy": " M"},
                                            "unmanaged": {"membership": "unmanaged"}, "ignored": {"membership": "unmanaged"},
                                            "remove-me": {"xy": " D"}, "link": CLEAN,
                                            ".config": {"summary": "changed"}, ".exact": {"summary": "changed"}}),
         step("Enter .exact and inspect extra. Enter .config, then press B.",
              'extra: C D ; missing targets contribute to parent summaries without fake rows; B returns to root.', absent=["script-ran"])),
    case("names", "Names, alignment and colors",
         step('Inspect space name, 日本語, quote"name, back\\slash, -dash and escaped newline/CR names. Toggle selection with Space; clear it with S.',
              'All are managed/clean. Hover and selection colors remain legible; columns align. W/d shows exact JSON filenames.',
              records={name: CLEAN for name in ['space name', '日本語', 'quote"name', 'back\\slash', '-dash', 'new\nline', 'carriage\rreturn']}),
         step("Use W/h to hide the guide. Resize the terminal, inspect clipping, then W/h to restore it.",
              "Normal layout is restored while hidden. W works at narrow sizes; columns clip without corrupting the list.")),
    case("refresh", "Manual refresh",
         step("Inspect local, then record the observation with W/p.", 'local: CMM .', records={"local": {"xy": "MM"}}),
         step("The guide matched source/local to dest/local. Press R.", 'local becomes C   . Brief unknown signs are allowed.',
              prep=[("match", "local")], files={"source/local": "local edit\n"}, records={"local": CLEAN}),
         step("The guide restored original source/local. Press R.", 'local returns to CMM .',
              prep=[("write", "source/local", "original\n")], records={"local": {"xy": "MM"}})),
    case("membership", "Membership discovery and removal",
         step("The guide added source/unmanaged. Press R.", 'unmanaged becomes C   .', prep=[("match", "unmanaged")], records={"unmanaged": CLEAN}),
         step("The guide removed only source/unmanaged. Press R.", 'unmanaged remains in dest with blank signs.',
              prep=[("remove", "source/unmanaged")], files={"dest/unmanaged": "other\n"}, absent=["source/unmanaged"], records={"unmanaged": {"membership": "unmanaged"}})),
    case("template-failure", "Template failure and recovery",
         step("The guide broke bad.tmpl. Press R.", 'bad: C!! ; clean: C   . A generic, throttled warning may appear without template contents.',
              prep=[("remove", "source/bad"), ("write", "source/bad.tmpl", "{{ .missing.field }}\n")], records={"bad": {"failed": True}, "clean": CLEAN}),
         step("The guide repaired bad.tmpl. Press R.", 'bad returns to C   .', prep=[("write", "source/bad.tmpl", "original\n")], records={"bad": CLEAN}),
         step("The guide added a broken descendant. Press R and inspect .config unhovered.", '.config keeps * with the partial underline.',
              prep=[("write", "source/dot_config/broken.tmpl", "{{ .missing.field }}\n")], records={".config": {"partial": True, "summary": "changed"}}),
         step("The guide removed the broken descendant. Press R.", 'The partial underline disappears.', prep=[("remove", "source/dot_config/broken.tmpl")], records={".config": {"partial": False}})),
    case("managed-failure", "Membership query failure",
         step("The guide enabled fail-managed. Press R.", 'Ordinary files: !   ; directories also have a summary error.',
              prep=[("write", "state/instrument/control", "fail-managed")], records={"clean": {"membership": "error"}}),
         step("The guide disabled fail-managed. Press R.", 'Known baseline signs return.', prep=[("remove", "state/instrument/control")], records={"local": {"xy": "MM"}, "clean": CLEAN})),
    case("navigation", "Navigation and tabs",
         step("Press N to enter .config, then record this step.", 'The .config destination opens.'),
         step("The guide matched source/source while you were away. Press B.", 'source becomes C   after acquisition.', prep=[("match", "source")], records={"source": CLEAN}),
         step("Press G to open .config in a new tab; H returns to tab zero.", 'The root source row stays clean.', records={"source": CLEAN})),
    case("theme", "Theme override and flavor fallback",
         step("Inspect local with the default theme, then record this step.", "Default CMM signs appear before changing theme.", records={"local": {"xy": "MM"}}),
         step("The guide installed a disposable flavor and theme. Press Y; inspect local unhovered.", 'Wide 界 comes from the theme; m and orange modified text come from the flavor. Rows align; epoch is unchanged.', prep=[("theme", "custom")], special="theme-custom"),
         step("The guide restored the base theme. Press Y.", 'Default signs return; status epoch stays unchanged.', prep=[("theme", "base")], special="theme-base")),
    case("add-forget", "Add, Re-add and Forget",
         step("Hover unmanaged. Press a (direct Add), then Enter after output.", 'The file becomes managed.', files={"source/unmanaged": "other\n", "dest/unmanaged": "other\n"}),
         step("The guide edited dest/unmanaged. Hover it; C then r (Re-add), then Enter.", 'Source records the destination edit.', prep=[("write", "dest/unmanaged", "changed by destination\n")], files={"source/unmanaged": "changed by destination\n"}),
         step("Hover unmanaged; press f (Forget), then n at plugin confirmation.", 'Cancellation preserves source and destination.', files={"source/unmanaged": "changed by destination\n", "dest/unmanaged": "changed by destination\n"}),
         step("Press f again; review every plugin page, answer y; answer y at the native prompt, then Enter.", 'Source entry disappears; destination remains.', absent=["source/unmanaged"], files={"dest/unmanaged": "changed by destination\n"})),
    case("destroy", "Destroy and shallow-directory rejection",
         step("Hover clean; press x; review plugin pages and accept plugin/native prompts; Enter after output.", 'Source and destination clean disappear; file list updates.', absent=["source/clean", "dest/clean"]),
         step("Hover .exact; press D (destroy --recursive=false).", 'Rejected before any confirmation; children stay intact.', files={"source/exact_dot_exact/keep": "same\n", "dest/.exact/keep": "same\n"}, no_action="destroy", special="no-new-destroy")),
    case("apply", "Scoped Apply, decline and accept",
         step("Hover source; press p; read diff; Enter; decline plugin confirmation with n.", 'Destination stays original; pending script is not run.', files={"dest/source": "original\n"}, absent=["script-ran"]),
         step("Press p again; read diff; Enter; accept confirmation with y; Enter after apply.", 'Destination matches source, becomes clean; unrelated script is not run.', files={"dest/source": "source edit\n"}, absent=["script-ran"])),
    case("template-add", "Template Add and protected Re-add",
         step("Hover unmanaged; press t (Add --template), then Enter.", 'A source template is created.', special="template-added"),
         step("The guide changed dest/unmanaged. Press r, then Enter if there is output.", 'Re-add leaves the original template unchanged.', prep=[("write", "dest/unmanaged", "new destination\n")], files={"source/unmanaged.tmpl": "other\n"})),
    case("encryption", "Disposable encrypted Add",
         step("Hover unmanaged; press z (Add --encrypt), then Enter.", 'Disposable age encryption works without personal credentials; destination stays readable.', files={"dest/unmanaged": "other\n"}, special="encrypted-added"), setup=[("age",)]),
    case("mixed", "Mixed selection rejection",
         step("Select clean with Space; select unmanaged with Space; press e.", 'The entire Edit is rejected. No editor runs.', files={"source/clean": "original\n", "dest/unmanaged": "other\n"}, no_action="edit"),
         step("Press S to clear selection. Hover .config; press e.", 'Directory Edit asks you to select files inside; no editor runs.', no_action="edit")),
    case("edit", "Plain Edit ignores config apply/watch",
         step("Hover source; press e. In the fixture editor type edited by fixture and Enter; Enter after command output.", 'Source changes; destination stays original despite apply=true/watch=true.', files={"source/source": "edited by fixture\n", "dest/source": "original\n"}), setup=[("editor", "manual")]),
    case("edit-apply", "Edit and Apply cancellation and acceptance",
         step("Hover source; press E. Type edited by fixture and Enter; Enter after edit and diff; decline apply with n.", 'Source edit survives; destination stays original.', files={"source/source": "edited by fixture\n", "dest/source": "original\n"}),
         step("Press E; type accepted edit and Enter; Enter after edit and diff; accept apply with y; Enter after apply.", 'Destination and source both contain accepted edit.', files={"source/source": "accepted edit\n", "dest/source": "accepted edit\n"}), setup=[("editor", "manual")]),
    case("interrupt", "Editor interruption",
         step("Hover source; press E. At fixture editor input press Ctrl-C; Enter after failure output.", 'Yazi returns, stays usable, and neither source nor destination changes.', files={"source/source": "source edit\n", "dest/source": "original\n"}), setup=[("editor", "manual")]),
    case("diff-script", "Diff and pending script",
         step("Hover .config; press d; inspect diff, then Enter.", 'Diff is readable; script has not run.', absent=["script-ran"]),
         step("Press p; inspect the full scoped diff, including the pending script; Enter; approve with y; Enter after apply.", 'new is created and script-ran exists only now.', files={"dest/.config/new": "new\n", "script-ran": ""})),
    case("visual", "Visual range, direct action and menu",
         step("Press 1 to hover range-a; v then j then j; press a; review all 3 paths, approve y, then Enter.", 'All 3 files are added; multi-target confirmation is required.', files={f"source/range-{c}": f"range {c}\n" for c in "abc"}),
         step("Press S. Press 2 to hover menu-a; v then j then j; press C then a; review 3 paths, approve y, then Enter.", 'The menu captures the complete visual range too.', files={f"source/menu-{c}": f"menu {c}\n" for c in "abc"}), setup=[("ranges",)]),
    case("visual-unset", "Visual unset and guide selection preservation",
         step("Press 1; Space then j then Space then j then Space. Press 1; V then j. Open W and Escape. Press a; Enter after output.", 'W preserves the visual unset range. Only range-c is added; range-a/b stay unmanaged.', files={"source/range-c": "range c\n"}, absent=["source/range-a", "source/range-b"]), setup=[("ranges",)]),
    case("cross-directory", "Selections across directories",
         step("Press 3; select outside with Space. Press B; press 1; v then j then j; press a; review all 4 paths, approve y; Enter.", 'The selected .config/outside and the 3 root files are all added.', files={**{f"source/range-{c}": f"range {c}\n" for c in "abc"}, "source/dot_config/outside": "outside\n"}), setup=[("ranges",)]),
    case("source-protection", "Source directory and ancestor protection",
         step("Hover .local; press x, then D. Enter .local/share; hover chezmoi; press x.", 'Every operation is rejected before native destroy; unrelated source state survives.', files={"dest/.local/share/chezmoi/dot_bashrc": "unrelated\n", "dest/.local/share/chezmoi/dot_local/bin/tool": "tool\n", "dest/.local/bin/tool": "tool\n"}, no_action="destroy"), setup=[("nested-source",)]),
    case("confirmation", "Confirmation pages, resizing and small pane",
         step("Press 4 to select every long/control/deep target. Press x; review every page with y but cancel the final page with n.", 'Every escaped path is visible across pages; no target disappears.', special="long-preserved"),
         step("Press x at a wide size; resize narrower while on page 1; answer y, inspect restart; cancel n.", 'Pane resized restarts review from page 1; all files survive.', special="long-preserved"),
         step("Use W/h to hide guide; resize terminal to 40x12 or smaller; press x. Enlarge again, restore guide with W/h.", 'A pane below 32 columns or 8 rows asks to enlarge; all files survive.', special="long-preserved"), setup=[("long",)]),
    case("git", "git.yazi coexistence",
         step("Inspect local and other untracked rows hovered and unhovered.", 'G appears before chezmoi signs; CMM remains visible and selection colors work.', records={"local": {"xy": "MM"}}), optional="git"),
]
